services:
  - type: web
    name: seguimiento-entregas
    env: python
    runtime: python3.11 # ← Esto fuerza una versión compatible

    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput

    startCommand: gunicorn seguimiento_paquetes.wsgi
    plan: free
    region: oregon

    envVars:
      - key: SECRET_KEY
        value: django-insecure-una-clave-super-secreta

      - key: DJANGO_SETTINGS_MODULE
        value: seguimiento_paquetes.settings

      - key: DEBUG
        value: False

      - key: ALLOWED_HOSTS
        value: seguimiento-entregas.onrender.com

      - key: DATABASE_URL
        value: sqlite:///db.sqlite3

      # Variables opcionales para funcionalidades avanzadas
      - key: GOOGLE_MAPS_API_KEY
        value: TU_CLAVE_DE_MAPAS

      - key: FIREBASE_CONFIG_JSON
        value: TU_JSON_EN_STRING
