# Generated by Django 5.2.4 on 2025-07-12 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrega',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='codigo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_ruta', 'En ruta'), ('entregada', 'Entregada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='repartidor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
